version: '3.4'

services:
  new-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=0
      no_cache: true
    # image: calciumion/new-api:latest  # 注释掉远程镜像
    container_name: mufy-new-api
    restart: always
    command: --log-dir /app/logs
    network_mode: "host"  # 使用宿主机网络
    # ports:
    #   - "3020:3000"  # 使用host网络模式时不需要端口映射
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=newapi2:418830073xX_@tcp(127.0.0.1:3306)/newapi2?charset=utf8mb4&parseTime=True&loc=Local
      - TZ=Asia/Shanghai
      - PORT=3020
      - ERROR_LOG_ENABLED=true # 是否启用错误日志记录
    #      - TIKTOKEN_CACHE_DIR=./tiktoken_cache  # 如果需要使用tiktoken_cache，请取消注释
    #      - SESSION_SECRET=random_string  # 多机部署时设置，必须修改这个随机字符串！！！！！！！
    #      - NODE_TYPE=slave  # Uncomment for slave node in multi-node deployment
    #      - SYNC_FREQUENCY=60  # Uncomment if regular database syncing is needed
    #      - FRONTEND_BASE_URL=https://openai.justsong.cn  # Uncomment for multi-node deployment with front-end URL

    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3
